### ISSUE TITLE
ventus_patch build problem

### ISSUE THREAD

**Issue by wenhu1024** [xlinsist/triton-benchmark#8]
i change LLVMEnums.td follow [llvm-project-0001-Add-CallingConvention-of-Ventus-kernel.patch](https://github.com/xlinsist/triton-benchmark/blob/main/patch/llvm-project-0001-Add-CallingConvention-of-Ventus-kernel.patch).
<br>
what i modify is below:
`def CConvVENTUS_KERNEL : LLVM_EnumAttrCase<"VENTUS_KERNEL", "ventus_kernelcc",
                                         "VENTUS_KERNEL", 102>;`
<br>
`def CConvEnum : LLVM_CEnumAttr<
    "CConv",
    "::llvm::CallingConv",
    "Calling Conventions",
    [CConvC, CConvFast, CConvCold, CConvGHC, CConvHiPE,
     CConvAnyReg, CConvPreserveMost, CConvPreserveAll, CConvSwift,
     CConvCXXFastTLS, CConvTail, CConvCFGuard_Check, CConvSwiftTail,
     CConvX86_StdCall, CConvX86_FastCall, CConvARM_APCS,
     CConvARM_AAPCS, CConvARM_AAPCS_VFP, CConvMSP430_INTR, CConvX86_ThisCall,
     CConvPTX_Kernel, CConvPTX_Device, CConvSPIR_FUNC, CConvSPIR_KERNEL,
     CConvIntel_OCL_BI, CConvX86_64_SysV, CConvWin64, CConvX86_VectorCall,
     CConvHHVM, CConvHHVM_C, CConvX86_INTR, CConvAVR_INTR, CConvAVR_BUILTIN,
     CConvAMDGPU_VS, CConvAMDGPU_GS, CConvAMDGPU_CS, CConvAMDGPU_KERNEL,
     CConvX86_RegCall, CConvAMDGPU_HS, CConvMSP430_BUILTIN, CConvAMDGPU_LS,
     CConvAMDGPU_ES, CConvAArch64_VectorCall, CConvAArch64_SVE_VectorCall,
     CConvWASM_EmscriptenInvoke, CConvAMDGPU_Gfx, CConvM68k_INTR, CConvVENTUS_KERNEL
    ]> {
  let cppNamespace = "::mlir::LLVM::cconv";
}`
<br>
and then i `cd ~/llvm-project/build && ninja`
<br>
but i get error message
`~/llvm-project/build/tools/mlir/include/mlir/Dialect/LLVMIR/LLVMConversionEnumsToLLVM.inc:378:54: 
     error: no member named 'VENTUS_KERNEL' in namespace 'llvm::CallingConv'
    return static_cast<int64_t>(::llvm::CallingConv::VENTUS_KERNEL);
                                ~~~~~~~~~~~~~~~~~~~~~^
1 error generated.`
<br>
Is there something wrong with me?

**Comment by wenhu1024** [comment]
@xvyv99

**Comment by xvyv99** [comment]
You might not be using the llvm-project from ventus-gpgpu, or the enumeration value of VENTUS_KERNEL should match the value defined in llvm/include/llvm/IR/CallingConv.h. This explains why I chose 104 instead of 102 as the enumeration value.
